//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.13 at 08:37:18 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.jasig.org/uportal/web/skin", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.jasig.portal.web.skin;
